### ISSUE TITLE
Issue on 1.19

### ISSUE THREAD

**Issue by TheMeq** [benwoo1110/Multiverse-CommandDestination#1]
Hi, I am using Wild v4.4.5 with Multiverse-CommandDestination v1.2.2 and I get the following stack trace whenever I use the portal. 

I can run the command manually without a problem. 

[18:46:47 ERROR]: Could not pass event MVPortalEvent to Multiverse-CommandDestination v1.2.2
org.bukkit.command.CommandException: Unhandled exception executing command 'wild' in plugin Wild v4.4.5-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:907) ~[paper-1.19.jar:git-Paper-31]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:959) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at dev.benergy10.multiversecommanddestination.commandexecutorapi.handlers.ConsoleHandler.execute(ConsoleHandler.java:10) ~[Multiverse-CommandDestination-1.2.2.jar:?]
        at dev.benergy10.multiversecommanddestination.commandexecutorapi.Command.execute(Command.java:22) ~[Multiverse-CommandDestination-1.2.2.jar:?]
        at dev.benergy10.multiversecommanddestination.commandexecutorapi.CommandGroup.lambda$executeAll$0(CommandGroup.java:20) ~[Multiverse-CommandDestination-1.2.2.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.benergy10.multiversecommanddestination.commandexecutorapi.CommandGroup.executeAll(CommandGroup.java:20) ~[Multiverse-CommandDestination-1.2.2.jar:?]
        at dev.benergy10.multiversecommanddestination.MultiverseCommandDestination.runCommand(MultiverseCommandDestination.java:70) ~[Multiverse-CommandDestination-1.2.2.jar:?]
        at dev.benergy10.multiversecommanddestination.MultiverseListeners$PortalListener.onPortal(MultiverseListeners.java:63) ~[Multiverse-CommandDestination-1.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-31]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:160) ~[Multiverse-Portals-4.2.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor489.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-31]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1535) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-31]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: How did we get here?
        at io.wildernesstp.command.WildCommand.execute(WildCommand.java:135) ~[WildernessTp.jar:?]
        at io.wildernesstp.command.BaseCommand.onCommand(BaseCommand.java:140) ~[WildernessTp.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 37 more

**Comment by TheMeq** [comment]
nvm, seems to be an issue with Wild, not your plugin.
